services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABSE}
      - POSTGRES_USER=${PG_USER}
    command: postgres -c stats_temp_directory=/tmp
    restart: unless-stopped
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
